#!/bin/bash
if [ $1 == '-start' ]
then
echo "Starting the command"
#adk -start operations
#start monitoring
#connect to the network
#advertise free resources (memory)

fi

val=0
val1=0
for var in "$@"
do
if [ $var == "-f" ]
then
val=1
fi
if [ $var == "-d" ]
then
val1=1
fi
if [ $val == 1 -a $val1 == 0 -a $var != '-f' ]
then
echo "Program file is $var"
fi
if [ $val == 1 -a $val1 == 1 -a $var != '-d' ]
then
echo "Dependency files are $var"
fi
done


